//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_HelloWorld.WS_HelloWorldSoap")]
    public interface WS_HelloWorldSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément name de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldResponse HelloWorld(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldResponse> HelloWorldAsync(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément name de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldEnglish", ReplyAction="*")]
        Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishResponse HelloWorldEnglish(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldEnglish", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishResponse> HelloWorldEnglishAsync(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldEnglishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldEnglish", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequestBody Body;
        
        public HelloWorldEnglishRequest() {
        }
        
        public HelloWorldEnglishRequest(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldEnglishRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public HelloWorldEnglishRequestBody() {
        }
        
        public HelloWorldEnglishRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldEnglishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldEnglishResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishResponseBody Body;
        
        public HelloWorldEnglishResponse() {
        }
        
        public HelloWorldEnglishResponse(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldEnglishResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldEnglishResult;
        
        public HelloWorldEnglishResponseBody() {
        }
        
        public HelloWorldEnglishResponseBody(string HelloWorldEnglishResult) {
            this.HelloWorldEnglishResult = HelloWorldEnglishResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_HelloWorldSoapChannel : Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_HelloWorldSoapClient : System.ServiceModel.ClientBase<Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap>, Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap {
        
        public WS_HelloWorldSoapClient() {
        }
        
        public WS_HelloWorldSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_HelloWorldSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_HelloWorldSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_HelloWorldSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldResponse Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap.HelloWorld(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string name) {
            Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequestBody();
            inValue.Body.name = name;
            Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldResponse retVal = ((Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldResponse> Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap.HelloWorldAsync(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldResponse> HelloWorldAsync(string name) {
            Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldRequestBody();
            inValue.Body.name = name;
            return ((Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishResponse Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap.HelloWorldEnglish(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequest request) {
            return base.Channel.HelloWorldEnglish(request);
        }
        
        public string HelloWorldEnglish(string name) {
            Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequestBody();
            inValue.Body.name = name;
            Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishResponse retVal = ((Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap)(this)).HelloWorldEnglish(inValue);
            return retVal.Body.HelloWorldEnglishResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishResponse> Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap.HelloWorldEnglishAsync(Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequest request) {
            return base.Channel.HelloWorldEnglishAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishResponse> HelloWorldEnglishAsync(string name) {
            Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.HelloWorldEnglishRequestBody();
            inValue.Body.name = name;
            return ((Client_WS_SOAP_HelloWorld.ServiceReference_HelloWorld.WS_HelloWorldSoap)(this)).HelloWorldEnglishAsync(inValue);
        }
    }
}
