//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LossByPart", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LossByPart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartCodeField;
        
        private decimal TotalLossField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PartCode {
            get {
                return this.PartCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartCodeField, value) != true)) {
                    this.PartCodeField = value;
                    this.RaisePropertyChanged("PartCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal TotalLoss {
            get {
                return this.TotalLossField;
            }
            set {
                if ((this.TotalLossField.Equals(value) != true)) {
                    this.TotalLossField = value;
                    this.RaisePropertyChanged("TotalLoss");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FinancialData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartCodeField;
        
        private decimal TotalCostField;
        
        private decimal TotalProfitField;
        
        private decimal TotalLossField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PartCode {
            get {
                return this.PartCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartCodeField, value) != true)) {
                    this.PartCodeField = value;
                    this.RaisePropertyChanged("PartCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal TotalCost {
            get {
                return this.TotalCostField;
            }
            set {
                if ((this.TotalCostField.Equals(value) != true)) {
                    this.TotalCostField = value;
                    this.RaisePropertyChanged("TotalCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal TotalProfit {
            get {
                return this.TotalProfitField;
            }
            set {
                if ((this.TotalProfitField.Equals(value) != true)) {
                    this.TotalProfitField = value;
                    this.RaisePropertyChanged("TotalProfit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal TotalLoss {
            get {
                return this.TotalLossField;
            }
            set {
                if ((this.TotalLossField.Equals(value) != true)) {
                    this.TotalLossField = value;
                    this.RaisePropertyChanged("TotalLoss");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Financial_of_Production.WS_financial_of_productionSoap")]
    public interface WS_financial_of_productionSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetPartWithGreatestLossResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartWithGreatestLoss", ReplyAction="*")]
        Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossResponse GetPartWithGreatestLoss(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPartWithGreatestLoss", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossResponse> GetPartWithGreatestLossAsync(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalProductionCosts", ReplyAction="*")]
        decimal GetTotalProductionCosts(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalProductionCosts", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> GetTotalProductionCostsAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalProfit", ReplyAction="*")]
        decimal GetTotalProfit(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalProfit", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> GetTotalProfitAsync(System.DateTime startDate, System.DateTime endDate);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetTotalLossByPartResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalLossByPart", ReplyAction="*")]
        Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartResponse GetTotalLossByPart(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalLossByPart", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartResponse> GetTotalLossByPartAsync(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément partCode de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetailedFinancialData", ReplyAction="*")]
        Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataResponse GetDetailedFinancialData(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetailedFinancialData", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataResponse> GetDetailedFinancialDataAsync(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartWithGreatestLossRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartWithGreatestLoss", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequestBody Body;
        
        public GetPartWithGreatestLossRequest() {
        }
        
        public GetPartWithGreatestLossRequest(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPartWithGreatestLossRequestBody {
        
        public GetPartWithGreatestLossRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartWithGreatestLossResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartWithGreatestLossResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossResponseBody Body;
        
        public GetPartWithGreatestLossResponse() {
        }
        
        public GetPartWithGreatestLossResponse(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPartWithGreatestLossResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPartWithGreatestLossResult;
        
        public GetPartWithGreatestLossResponseBody() {
        }
        
        public GetPartWithGreatestLossResponseBody(string GetPartWithGreatestLossResult) {
            this.GetPartWithGreatestLossResult = GetPartWithGreatestLossResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalLossByPartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalLossByPart", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequestBody Body;
        
        public GetTotalLossByPartRequest() {
        }
        
        public GetTotalLossByPartRequest(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalLossByPartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime endDate;
        
        public GetTotalLossByPartRequestBody() {
        }
        
        public GetTotalLossByPartRequestBody(System.DateTime startDate, System.DateTime endDate) {
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalLossByPartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalLossByPartResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartResponseBody Body;
        
        public GetTotalLossByPartResponse() {
        }
        
        public GetTotalLossByPartResponse(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalLossByPartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.LossByPart[] GetTotalLossByPartResult;
        
        public GetTotalLossByPartResponseBody() {
        }
        
        public GetTotalLossByPartResponseBody(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.LossByPart[] GetTotalLossByPartResult) {
            this.GetTotalLossByPartResult = GetTotalLossByPartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDetailedFinancialDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDetailedFinancialData", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequestBody Body;
        
        public GetDetailedFinancialDataRequest() {
        }
        
        public GetDetailedFinancialDataRequest(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDetailedFinancialDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partCode;
        
        public GetDetailedFinancialDataRequestBody() {
        }
        
        public GetDetailedFinancialDataRequestBody(string partCode) {
            this.partCode = partCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDetailedFinancialDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDetailedFinancialDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataResponseBody Body;
        
        public GetDetailedFinancialDataResponse() {
        }
        
        public GetDetailedFinancialDataResponse(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDetailedFinancialDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.FinancialData GetDetailedFinancialDataResult;
        
        public GetDetailedFinancialDataResponseBody() {
        }
        
        public GetDetailedFinancialDataResponseBody(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.FinancialData GetDetailedFinancialDataResult) {
            this.GetDetailedFinancialDataResult = GetDetailedFinancialDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_financial_of_productionSoapChannel : Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_financial_of_productionSoapClient : System.ServiceModel.ClientBase<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap>, Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap {
        
        public WS_financial_of_productionSoapClient() {
        }
        
        public WS_financial_of_productionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_financial_of_productionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_financial_of_productionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_financial_of_productionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossResponse Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap.GetPartWithGreatestLoss(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequest request) {
            return base.Channel.GetPartWithGreatestLoss(request);
        }
        
        public string GetPartWithGreatestLoss() {
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequestBody();
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossResponse retVal = ((Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap)(this)).GetPartWithGreatestLoss(inValue);
            return retVal.Body.GetPartWithGreatestLossResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossResponse> Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap.GetPartWithGreatestLossAsync(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequest request) {
            return base.Channel.GetPartWithGreatestLossAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossResponse> GetPartWithGreatestLossAsync() {
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetPartWithGreatestLossRequestBody();
            return ((Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap)(this)).GetPartWithGreatestLossAsync(inValue);
        }
        
        public decimal GetTotalProductionCosts(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetTotalProductionCosts(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<decimal> GetTotalProductionCostsAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetTotalProductionCostsAsync(startDate, endDate);
        }
        
        public decimal GetTotalProfit(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetTotalProfit(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<decimal> GetTotalProfitAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetTotalProfitAsync(startDate, endDate);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartResponse Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap.GetTotalLossByPart(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequest request) {
            return base.Channel.GetTotalLossByPart(request);
        }
        
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.LossByPart[] GetTotalLossByPart(System.DateTime startDate, System.DateTime endDate) {
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartResponse retVal = ((Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap)(this)).GetTotalLossByPart(inValue);
            return retVal.Body.GetTotalLossByPartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartResponse> Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap.GetTotalLossByPartAsync(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequest request) {
            return base.Channel.GetTotalLossByPartAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartResponse> GetTotalLossByPartAsync(System.DateTime startDate, System.DateTime endDate) {
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetTotalLossByPartRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            return ((Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap)(this)).GetTotalLossByPartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataResponse Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap.GetDetailedFinancialData(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequest request) {
            return base.Channel.GetDetailedFinancialData(request);
        }
        
        public Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.FinancialData GetDetailedFinancialData(string partCode) {
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequestBody();
            inValue.Body.partCode = partCode;
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataResponse retVal = ((Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap)(this)).GetDetailedFinancialData(inValue);
            return retVal.Body.GetDetailedFinancialDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataResponse> Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap.GetDetailedFinancialDataAsync(Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequest request) {
            return base.Channel.GetDetailedFinancialDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataResponse> GetDetailedFinancialDataAsync(string partCode) {
            Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequest inValue = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequest();
            inValue.Body = new Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.GetDetailedFinancialDataRequestBody();
            inValue.Body.partCode = partCode;
            return ((Client_WS_SOAP_HelloWorld.ServiceReference_Financial_of_Production.WS_financial_of_productionSoap)(this)).GetDetailedFinancialDataAsync(inValue);
        }
    }
}
